[2025-06-08 13:19:45,199 INFO] Parsed arguments: {'model': 'meta-llama/Llama-3.2-1B', 'tasks': ['winogrande'], 'num_fewshot': 0, 'seed': 42, 'limit': None, 'batch_size': 4, 'output_dir': 'results/meta-llama/Llama-3.2-1B_winogrande_english', 'cache_opt': False, 'double_buffer': False, 'temperature': 0.7, 'engine': 'hf', 'language': 'english'}
[2025-06-08 13:21:02,732 INFO] Evaluating winogrande...
[2025-06-08 13:21:02,736 ERROR] Exception during evaluate():
[2025-06-08 13:21:02,736 ERROR] Traceback (most recent call last):
  File "/home/s1/jypark/twice/main.py", line 125, in main
    df =evaluate(args, tasks,args.language)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s1/jypark/twice/cli_evaluator.py", line 79, in evaluate
    dataset, answer, og_dataset = load(name=task,
                                 ^^^^^^^^^^^^^^^
  File "/home/s1/jypark/twice/loader/load.py", line 34, in load
    raise RuntimeError("OPENAI_API_KEY environment variable not set")
RuntimeError: OPENAI_API_KEY environment variable not set

